name: CI

on:
  push:
    branches: [main, MVP, docs]
  pull_request:
    branches: [main, MVP, docs]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Install asimov package
        run: poetry run pip install -e .
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          mkdir -p coverage-reports
          poetry run pytest --cov=src/asimov --cov-report=xml:coverage-reports/coverage.xml --cov-config=pyproject.toml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-reports/coverage.xml
          fail_ci_if_error: true